version: "3.9"

services:
  web:
    container_name: fast-api-template-web
    build:
      context: .
      dockerfile: ./build/web.dockerfile
    env_file:
      - ./build/.env
    volumes:
      - ./src:/app/src
    ports:
      - 10500:10500
    command: sh -c  "gunicorn main:app --bind 0.0.0.0:10500 --workers 1 --worker-class uvicorn.workers.UvicornWorker"
