version: "3.9"

services:
  web:
    container_name: fast-api-template-test
    build:
      context: .
      dockerfile: ./build/web.dockerfile
    env_file:
      - ./build/.env
    volumes:
      - ./src:/app/src
    command: sh -c  "coverage run -m pytest && coverage report"
